# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # flutter_test:
  #   name: Run flutter test and analyze
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-java@v1
  #       with:
  #         java-version: "12.x"
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: "3.3.0"
      # - run: flutter pub get
      # - run: flutter analyze
      # - run: flutter test

  # build_ios:
  #   name: Build flutter(IOS)
  #   needs: [flutter_test]
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         channel: "stable"
  #         architecture: x64
  #     - run: flutter pub get
  #     - run: flutter clean
  #     - run:  flutter build ipa --export-options-plist=ExportOptions.plist cd ios && fastlane beta ipa:../build/ios/ipa/YourBundleName.ipa
  #     - name: Push IOS to Releases
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: release-ipa
  #         # Path to the release files
  #         path: build/ios/ipa/*.ipa
  # path: /Users/runner/work/kachuwa-app-dev/kachuwa-app-dev/build/ios/iphoneos/*

  build_and_release:
    name: Build and Release Text File
    # needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: Create Text File
        run: echo "Hello, this is a sample text file." > sample.txt
  
      - name: Upload Text File
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: sample.txt
  
      - name: Release Text File
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Release v1.0.${{ github.run_number }}
          body: "Release Notes for v1.0.${{ github.run_number }}"
          draft: false
          prerelease: false
  
      - name: Attach Text File to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: sample.txt
          asset_name: sample.txt
          asset_content_type: "text/plain"
          token: ${{ secrets.GITHUB_TOKEN }}
