name: Release Text File to Different Repo

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_release:
    name: Build and Release Text File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Text File
        run: echo "Hello, this is a sample text file." > sample.txt

      - name: Upload Text File
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: sample.txt

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Release v1.0.${{ github.run_number }}
          body: "Release Notes for v1.0.${{ github.run_number }}"
          draft: false
          prerelease: false
          owner: runzun1987  # Replace with the owner of the target repository
          repo: kachuwaAppPublicToUse   # Replace with the name of the target repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

      - name: Attach Text File to Release
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: sample.txt
          asset_name: sample.txt
          asset_content_type: "text/plain"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
